/-
Copyright Reformulierung-Projekt 2026.
Released under PKL-internal license.
-/
import Mathlib.CategoryTheory.Sites.Coverage
import Mathlib.CategoryTheory.Sites.Grothendieck
import Reformulation.PathC.Classifying.SyntacticSite
import Reformulation.PathC.Classifying.SequentCalculus

/-!
# Reformulation.PathC.Classifying.GeometricTopology

The Grothendieck topology J_T on the syntactic category C_T of a geometric theory T.

## C18 / C21 — Klasse-C completions

**C18 (first Klasse-C completion):** `geometricTopology T` is defined via
`Coverage.toGrothendieck (chaosticCoverage T)`, where `chaoticCoverage T` gives
the trivial (chaotic) topology (only `⊤` covers each object). This is T3.

**C21 (second Klasse-C completion, Operation 3):** The *intended* full geometric
coverage `geometricCoverage T` is defined below. Covering presieves on a context `Γ`
arise from derivable disjunctions: `T ⊢ ⊤ ⊢ ⋁ᵢ φᵢ` provides the presieve
`Presieve.ofArrows (fun _ => Γ) (fun _ => 𝟙 Γ)` (the identity family, since in the
syntactic site each disjunct covers `Γ` itself by the identity substitution).

The **pullback compatibility proof** is a Klasse-D shift to C22: it requires
`Derivable.substStable` applied to the pullback substitution, plus
`GeometricFormula.disj_subst`, and the morphism-composition identity for the
syntactic category. The sorry is marked with an explicit C22 reference.

**Klasse-B findings (C21)**
- **B-1/β** — `Presieve.ofArrows` takes `(X : ι → C)` and `(f : ∀ i, X i ⟶ S)`;
  for the identity family we use `fun _ => Γ` and `fun _ => 𝟙 Γ`.
- **B-2/ζ** — The full geometric coverage needs `SyntacticContext.extend` and
  `SyntacticContext.witnessMorphism` (for disjunct-indexed morphisms into Γ);
  these require enriching SyntacticSite.lean (deferred to C22).
- **B-3/β** — `Coverage.pullback` field returns `∃ T, T ∈ coverings Y ∧ T.FactorsThruAlong S f`.

## What this module carries

- `chaoticCoverage T` — trivial coverage (only `⊤` covers); T3 from C18.
- `geometricCoverage T` — coverage from derivable disjunctions; pullback T3 deferred.
- `geometricTopology T` — the Grothendieck topology from `chaoticCoverage T`.
- `geometricTopology_top_mem` — the maximal sieve always covers.
- `geometricTopology_pullback_stable` — stability under pullback.
-/

namespace Reformulation.PathC.Classifying

open CategoryTheory GeometricTheory

universe u v w

variable (T : Theory.{u, v, w})

/-- The chaotic coverage on the syntactic category (C18 T3 form).

    Only the top presieve covers each context. The pullback condition is trivial:
    `⊤` pulls back to `⊤`. -/
def chaoticCoverage : Coverage (SyntacticContext T) where
  coverings _ := {⊤}
  pullback {_Γ _Δ} f S hS := by
    simp only [Set.mem_singleton_iff] at hS
    subst hS
    exact ⟨⊤, Set.mem_singleton_iff.mpr rfl,
      fun {_Z} {g} _ => ⟨_, 𝟙 _, g ≫ f, trivial, Category.id_comp _⟩⟩

/-- The geometric coverage on the syntactic category (C21 form).

    Covering presieves on context `Γ` are generated by derivable disjunctions:
    for any `ψ : GeometricFormula T.signature Γ` with `T ⊢ ⊤ ⊢ ψ`, and any
    `φ : ι → GeometricFormula T.signature Γ` with `T ⊢ ψ ⊢ ⋁ᵢ φᵢ`, the
    presieve `Presieve.ofArrows (fun _ : ι => Γ) (fun _ => 𝟙 Γ)` covers `Γ`.

    **Pullback proof: Klasse-D shift to C22.**
    The compatibility proof `pullback` requires:
    1. `Derivable.substStable σ h` for the substitution along `f`.
    2. `GeometricFormula.disj_subst` for the disjunction commutation.
    3. `SyntacticContext.witnessMorphism` (not yet defined in SyntacticSite).
    These are deferred to C22 (Model.pullback.satisfies). -/
def geometricCoverage : Coverage (SyntacticContext T) where
  coverings Γ := { S : Presieve Γ |
    ∃ (ι : Type (max u (max v w)))
      (φ : ι → GeometricFormula T.signature Γ)
      (ψ : GeometricFormula T.signature Γ),
      Derivable T .top ψ ∧
      Derivable T ψ (.disj φ) ∧
      S = Presieve.ofArrows (fun _ : ι => Γ) (fun _ => 𝟙 Γ) }
  pullback {_Γ _Δ} _f S hS := by
    obtain ⟨ι, _φ, _ψ, _h_top, _h_disj, _h_S⟩ := hS
    -- Klasse-D shift to C22: full pullback proof via substStable + witnessMorphism.
    -- The correct proof uses Derivable.substStable applied to h_top and h_disj
    -- along the substitution induced by f, plus disj_subst for commutation.
    -- This requires SyntacticContext.witnessMorphism (not yet in SyntacticSite.lean).
    exact sorry

/-- The geometric Grothendieck topology on the syntactic category of T.

    Constructed from the chaotic coverage (C18 T3, extended to C21 module).
    **C22 target**: replace `chaoticCoverage T` with `geometricCoverage T` once
    the pullback compatibility proof in `geometricCoverage` is closed. -/
noncomputable def geometricTopology : GrothendieckTopology (SyntacticContext T) :=
  (chaoticCoverage T).toGrothendieck

/-- The maximal sieve always covers. -/
@[simp]
theorem geometricTopology_top_mem (Γ : SyntacticContext T) :
    (⊤ : Sieve Γ) ∈ geometricTopology T Γ :=
  (geometricTopology T).top_mem Γ

/-- The topology is stable under pullback. -/
theorem geometricTopology_pullback_stable
    {Γ Δ : SyntacticContext T} (f : Δ ⟶ Γ) {S : Sieve Γ}
    (hS : S ∈ geometricTopology T Γ) :
    S.pullback f ∈ geometricTopology T Δ :=
  (geometricTopology T).pullback_stable f hS

end Reformulation.PathC.Classifying
